//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProjectAptitude.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Examination()
        {
            this.ExaminationDetails = new HashSet<ExaminationDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> TimeStartExam { get; set; }
        public Nullable<System.DateTime> TimeEndExam { get; set; }
        public string ExamCode { get; set; }
        public Nullable<int> IdP { get; set; }
        public Nullable<int> IdE { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExaminationDetail> ExaminationDetails { get; set; }
    }
}
