//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProjectAptitude.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExaminationDetail
    {
        public int ID { get; set; }
        public Nullable<int> IDQuestion { get; set; }
        public Nullable<int> IDExam { get; set; }
        public Nullable<int> TotalMarks { get; set; }
    
        public virtual Examination Examination { get; set; }
        public virtual Question Question { get; set; }
    }
}
