//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProjectAptitude.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.ExaminationDetails = new HashSet<ExaminationDetail>();
        }
    
        public int ID { get; set; }
        public int QuestionTypeID { get; set; }
        public Nullable<int> Marks { get; set; }
        public string QuestionName { get; set; }
        public string OPA { get; set; }
        public string OPB { get; set; }
        public string OPC { get; set; }
        public string OPD { get; set; }
        public string COP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExaminationDetail> ExaminationDetails { get; set; }
        public virtual QuestionType QuestionType { get; set; }
    }
}
