//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProjectAptitude.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class User
    {
        public int UserID { get; set; }
        public string Email { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string GeneralKnowledgeExamMarks { get; set; }
        public string MathematicsExamMarks { get; set; }
        public string ComputerTechnologyExamMarks { get; set; }
        public Nullable<int> PositionID { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Image { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public Nullable<System.DateTime> DateExam { get; set; }
        public Nullable<bool> ExamStatus { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> Gender { get; set; }
    
        public virtual Position Position { get; set; }
    }
}
